name: Build to GCR
on: 
  push:
    branches:
      - master
env:
  IMAGE_NAME: gitops-app-fauji
  PROJECT_ID: horizontal-veld-327901
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Copy Code
        uses: actions/checkout@v1
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.3.0
        with: 
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${PROJECT_ID
          export_default_credentials: true
      - name: Build Docker Image
        run: docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }} 
      - name: Login to Registry
        run: gcloud auth configure-docker --quiet
      - name: Push to GCR
        run: docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:${{ github.sha }}
